apiVersion: v1
kind: Namespace
metadata:
  name: jeffersondevops

---

apiVersion: v1
kind: Service
metadata:
  name: jefferson-app-service
  namespace: jeffersondevops
spec:
  type: NodePort
  selector:
    app: webservice
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080
      nodePort: 30980

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jefferson-app-deployment
  namespace: jeffersondevops
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: jefferson-app
        image: jeffersonbcm/jefferson-app:0.1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: jeffersondevops
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: jeffersondevops
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:latest
